comment:
  single_comment: true          
  chat: true                   
  sections:
    - Summary                  
    - Walkthrough              
    - Changes                  
    - Estimated code review effort
  exclude_sections:
    - Poem                     
    - Pre-merge checks and finishing touches
    - Sequence Diagram(s)
    - Possibly related issues
  inline_comments: true        
  actionable_comment: true     
  nitpick_comment: true       
summary:
  enabled: true
  format: |
    ## Summary
    Concisely describe the pull request's main purpose, key fixes or features, and reference any closed issues here.
