apiVersion: v1
kind: Service
metadata:
  name: opsimate-backend-service
spec:
  type: LoadBalancer
  selector:
    app: opsimate-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001