apiVersion: v1
kind: Service
metadata:
  name: opsimate-backend-service
  labels:
    app: opsimate-backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: opsimate-backend
