name: Auto Label PRs

on:
  issues:
    types: [opened, edited]
  pull_request_target:    # use pull_request_target for PRs (runs with base repo permissions)
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/labeler.yml'
          sync-labels: true
