name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Enable Pnpm
        run: corepack enable

      - name: Clear pnpm cache
        run: pnpm store prune

      - name: Install dependencies
        run: pnpm ci

      - name: Build project
        run: pnpm run build

      - name: Lint apps/server
        run: |
          cd apps/server
          pnpm run lint -- --max-warnings=0

      - name: Lint packages/shared
        run: |
          cd packages/shared
          pnpm run lint -- --max-warnings=0

      - name: Test apps/server
        run: |
          cd apps/server
          pnpm test


      # Uncomment when ready
      # - name: Run tests
      #   run: npm run test
