name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get version from latest release
      id: version
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/opsimate/opsimate/releases/latest | jq -r '.name')
        VERSION=$(echo $LATEST_RELEASE | sed 's/Release v//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: opsimate
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and Push Docker Image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t opsimate/opsimate:${{ steps.version.outputs.version }} -t opsimate/opsimate:latest --push .
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        release_name: Release ${{ steps.version.outputs.tag }}
        draft: false
        prerelease: false
