name: Sync Version on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sync-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.ADMIN_PAT }}  

      - name: Get released version
        id: get_version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "RELEASE_TAG=$RELEASE_TAG_NAME" >> $GITHUB_ENV
          VERSION="$RELEASE_TAG_NAME"
          VERSION="${VERSION#v}"   # Remove leading 'v' if present
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set next version to released version (no increment)
        id: set_version
        run: |
          NEXT_VERSION="$VERSION"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          jq --arg ver "$NEXT_VERSION" '.version = $ver' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Commit and push version sync
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: sync version to ${{ env.NEXT_VERSION }} on release"
          branch: main
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}  # Important: replace default token with PAT
