name: Sync Version on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sync-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get released version
        id: get_version
        run: |
          echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"   # Remove leading 'v' if present
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set next version to released version (no increment)
        id: set_version
        run: |
          NEXT_VERSION="$VERSION"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          jq --arg ver "$NEXT_VERSION" '.version = $ver' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Commit and push version sync
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: sync version to ${{ env.NEXT_VERSION }} on release"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          branch: main
